name: Build Go Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build for multiple platforms
      run: make

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: dist/

    - name: Deploy
      run: |
        echo "${{ secrets.APP_SERVER_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.APP_SERVER_HOST }} "sudo systemctl stop sambilan-backend.service"
        scp -i private_key.pem -o StrictHostKeyChecking=no dist/app-linux-amd64 ubuntu@${{ secrets.APP_SERVER_HOST }}:/app/sambilan-backend.service
        ssh -i private_key.pem ubuntu@${{ secrets.APP_SERVER_HOST }} "sudo systemctl start sambilan-backend.service && sudo systemctl reload nginx"
